name: Build Release
on: [ push, pull_request ]
jobs:
  create-release:
    runs-on: 'ubuntu-22.04'
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create-release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          omitBody: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ${{ matrix.os }}
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04 ]
        platform:
          - 'linux-x64'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          pip3 install meson ninja packaging
          brew install automake nasm pkg-config
      - name: Build ${{ matrix.platform }}
        id: build-release
        run: ./build.sh $(cat LIBVIPS_VERSION) ${{ matrix.platform }}
      - name: Generate integrity checksums
        id: integrity
        run: ./integrity.sh
      - name: Upload Release Asset (.tar.gz)
        id: upload-release-asset-gz
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: libvips-*-${{ matrix.platform }}.tar.gz
          artifactContentType: application/gzip
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Asset (.integrity)
        id: upload-release-asset-integrity
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "*.integrity"
          artifactContentType: text/plain
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
